apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: amankr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: helloworld
        image: contregistrypractice.azurecr.io/hello:latest
        ports:
        - containerPort: 8080
    imagePullSecrets:
      - name: acr-secret