name: Java CI with Maven and Docker

on:
  push:
    branches:
      - master
      - feature
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: /home/runner/work/Hello_World_v1/Hello_World_v1/

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Run unit tests
        run: mvn test
        continue-on-error: false

      - name: ACR Login
        uses: azure/docker-login@v1
        with:
          login-server: contregistrypractice.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Push Docker image
        run: |
          docker build . -t contregistrypractice.azurecr.io/hello:${{ github.sha }}
          docker push contregistrypractice.azurecr.io/hello:${{ github.sha }}
      - name: Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'contregistrypractice.azurecr.io/hello:${{ github.sha }}'
          security-checks: 'vuln,secret,config'
          format: 'sarif'
          output: 'trivy-image-results.sarif'
          severity: 'CRITICAL,HIGH'

      # - name: Upload the scan result to GitHub Security
      #   uses: github/codeql-action/upload-sarif@v2
      #   with:
      #     sarif_file: 'trivy-image-results.sarif'
      #     category: 'image'
          
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
         push: true
         tags: ${{secrets.DOCKER_USERNAME}}/${{secrets.REPO_NAME}}:latest
         context: .
