name: Create resources using Terraform

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tflint-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v3

      - name: Cache plugin dir
        uses: actions/cache@v2
        with:
          path: ~/.tflint.d/plugins
          key: ${{ runner.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v2
        with:
          github_token: ${{ secrets.CI_GITHUB_TOKEN }}

      - name: Show TFLint version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init

      - name: Run TFLint
        id: tflint
        run: |
          tflint -f compact --recursive --force 2>&1 | tee tflint-out.txt
          if [ ! -s tflint-out.txt ]; then
            echo "TFLint run has no findings" >> tflint-out.txt
          else
            sed -i '1i*************' tflint-out.txt
            sed -i '1iTFLint Report' tflint-out.txt
          fi

      - name: TFLint Output in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          header: tflint-outputs
          recreate: true
          path: tflint-out.txt

  tfsec-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v3

      - name: Run TFSec and save output
        id: tfsec
        run: |
          tfsec --format sarif ./Terraform_code > tfsec_output.sarif.txt 2>&1 || true

      - name: Filter Failure Cases from TFSec Output
        run: grep -E "CRITICAL|HIGH" tfsec_output.sarif.txt > tfsec-failures.txt || true

      - name: TFSec Output in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          header: tfsec-outputs
          recreate: true
          path: tfsec-failures.txt

  checkov-check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v3

      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        continue-on-error: true

      - name: Checkov Output in PR
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}
          header: checkov-outputs
          recreate: true
          message: |
            ```
            ${{ steps.checkov.outputs.checkov_output }}
            ```

  format-terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v3

      - name: Format Terraform files
        run: terraform fmt -recursive
